# Examples of the Application of states.py

## Example 1

 Calling States() with default attributes:

In [3]:
import sys
import os

sys.path.insert(0, os.path.abspath('../../'))

from states import *

state = States()

Print a copy of:

* num_qubits_copy: number of qubits N --> default is N = 1.
* state_copy: initial state --> default is |0> = $\left[ 
\begin{array}{c}
1 \\
0
\end{array}
\right]
$.

In [4]:
num_qubits_copy = state.get_N()
state_copy = state.get_state()

print(num_qubits_copy)
print(state_copy)

1
[[1]
 [0]]


## Application of the norm function.

* Normalises state.

    - Taking number of qubits equal to two: N = 2
    - state:  $|\Psi> = \left[ 
\begin{array}{c}
1 \\
1 \\
1 \\
1
\end{array}
\right]
$.
    - Returns normalised state: $|\Psi> = \frac{1}{2}\left[ 
\begin{array}{c}
1 \\
1 \\
1 \\
1
\end{array}
\right]
$.


In [5]:
state_norm = norm(2, [[1],[1],[1],[1]])
print(state_norm)

[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Application of the tp function.

* Computes tensor product of state $|\Psi> = |\psi_1>\otimes|\psi_2 > $.

    - Taking state_1: $|\psi_1> = \left[ 
\begin{array}{c}
1 \\
0 
\end{array}
\right]
$ and state_2: $|\Psi_2> = \left[ 
\begin{array}{c}
0 \\
1 
\end{array}
\right]
$.
    - It will return tensor product of state: $|\Psi> = \left[ 
\begin{array}{c}
0 \\
1 \\
0 \\
0
\end{array}
\right]
$.

In [6]:
tensor_product = tp([[1],[0]],[[0],[1]])
print(tensor_product)

[[0]
 [1]
 [0]
 [0]]


## Application of the angle function.

* Provides initial state given polar ($\theta$) and azimuthal ($\phi$) angles.

    - Taking $\theta = 90^o$ and $\phi = 90^o$ with $|\Psi> = cos(\frac{\theta}{2})|0> + i sin(\frac{\theta}{2}) e^{i\phi}|1>$
    - It will return state: $|\Psi> = \frac{1}{\sqrt{2}} \left[ 
\begin{array}{c}
1 \\
i
\end{array}
\right]
$.


In [7]:
state_angle = angle(90, 90)
print(state_angle)

[[0.70710678+0.j        ]
 [0.        +0.70710678j]]


## Example 2

Calling States() but with different attributes:

 * number of qubits: N = 4.
 
 * state: State is a column vector formed of different built-in states to demonstrate how they're used.     
    - Here we use PhiPlus().state which corresponds to $|\phi^+>$ = $\frac{|00> + |11>}{\sqrt{2}} = \frac{1}{\sqrt{2}}\left[ 
    \begin{array}{c}
    1 \\
    0 \\
    0 \\
    1
    \end{array}
    \right]
    $
    - Tensor product of Zero().state (|0> = $\left[ 
\begin{array}{c}
1 \\
0 
\end{array}
\right]
$) and One().state (|0> = $\left[ 
\begin{array}{c}
0 \\
1 
\end{array}
\right]
$), which then correponds to |01> = $\left[ 
\begin{array}{c}
0 \\
1 \\
0 \\
0
\end{array}
\right]
$
    - The state then equals to $|\Psi> = \left[ 
\begin{array}{c}
\frac{1}{\sqrt{2}} \\
0 \\
0 \\
\frac{1}{\sqrt{2}} \\
0 \\
1 \\
0 \\
0
\end{array}
\right]
$

In [8]:
s1 = States(4, np.vstack((PhiPlus().state, tp(Zero().state, One().state))))

num_qubits_copy1 = s1.get_N()
state_copy1 = s1.get_state()

print(num_qubits_copy1)
print(state_copy1)


TypeError: The length of initial states list for 4 qubit(s) is not 8. It should be equal to 16.