# Examples of the application of states.py script.

## Example 1

### Calling States().

In [32]:
import sys
import os

current_dir = os.getcwd()
sys.path.append(current_dir)

from states import *

state = States()

### Print a copy of num_qubits_copy (number of qubits N) and state_copy (initial state 1).

In [33]:
num_qubits_copy = state.get_N()
state_copy = state.get_state()

print(num_qubits_copy)
print(state_copy)

1
[[1]
 [0]]


## Application of the norm function (normalises state).

In [34]:
state_norm = norm(2, [[1],[1],[1],[1]])
print(state_norm)

[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Application of the tp function (computes tensor product of state).

In [35]:
tensor_product = tp([[1],[0]],[[0],[1]])
print(tensor_product)

[[0]
 [1]
 [0]
 [0]]


## Application of the angle function (provides initial state given polar and azimuthal angles).

In [36]:
state_angle = angle(90, 90)
print(state_angle)

[[0.70710678+0.j        ]
 [0.        +0.70710678j]]


## Example 2

### Calling States() but with different attributes.

In [37]:
s1 = States(4, np.vstack((PhiPlus().state, tp(Zero().state, One().state))))

num_qubits_copy1 = s1.get_N()
state_copy1 = s1.get_state()

print(num_qubits_copy1)
print(state_copy1)


4
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]
 [0.        ]
 [1.        ]
 [0.        ]
 [0.        ]]
