# Examples of the application of the ''gates'' package

By Theo

This document showcases a few simple examples of how to initialise custom and in-built gates. For that, let us begin by calling the gates module.

In [1]:
import os
import sys
sys.path.insert(0, os.path.abspath('../../'))

import numpy as np
import gates

In order to call a gate, one needs to call its corresponding class. 
There are several classes that produce gates with varying degrees of freedom. Let us see some examples:

- Gate($n$, $U$): a general gate class applied on $n$ (`num_qubits` in the code) qubits being represented in the computational basis by matrix $U$ (`array` in the code).

Let us say $n=1$ and the gate we want to implement is the Hadamard gate:
\begin{equation}
U = H = \frac{1}{\sqrt{2}}
\begin{pmatrix}
1 & 1\\
1 & -1
\end{pmatrix}.	
\end{equation}

In this case, all we need to do is create the necessary array as input for a Gate class instance:

In [2]:
num_qubits = 1
array = np.array([[1,1],[1,-1]])/np.sqrt(2) 

# or can be a list it you apply the square root fraction to each term. Uncomment below to check this.

# array = [[1/np.sqrt(2),1/np.sqrt(2)],
#          [1/np.sqrt(2),-1/np.sqrt(2)]]

hadamard_gate = gates.Gate(num_qubits, array)

Now that we have an instance, we can check that it is correct by calling getter methods for the number of qubits, or the matrix components:

In [3]:
check_num_qubits = hadamard_gate.get_num_qubits()

print(f'The number of qubits of our gate is {check_num_qubits}.')

check_array = hadamard_gate.get_array()

print('The gate takes the form: \n', check_array)

The number of qubits of our gate is 1.
The gate takes the form: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


A neater and more controlled way to create a gate is by using the function `create_gate`.

In [4]:
new_hadamard = gates.create_gate(num_qubits, array)

# Check that it is indeed the gate from before:
check_new_array = new_hadamard.get_array()
print('The new gate takes the form: \n', check_new_array)

The new gate takes the form: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


And of course, for such a simple example, we have created a built-in gate: the `HGate`. Read the documentation for the complete list of built-in gates.

In [5]:
builtin_hadamard = gates.HGate()

# Check that it is indeed the gate from before:
check_builtin_array = builtin_hadamard.get_array()
print('The builtin gate takes the form: \n', check_builtin_array)

The builtin gate takes the form: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


The reason we say that the function create_gate() is controlled is because it implicitly tests for the unitarity of the gate.

Furthermore, if any prefactor is omitted, the function finds the prefactor and appends it to the gate.
Let us say we forgot to put the factor $\frac{1}{\sqrt{2}}$.

In [6]:
num_qubits = 1
scaled_array = [[1,1],[1,-1]]

still_hadamard = gates.create_gate(num_qubits, scaled_array)

check_still_hadamard = still_hadamard.get_array()
print('The gate takes the form: \n', check_builtin_array, ', \n it is a Hadamard.')

The gate takes the form: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] , 
 it is a Hadamard.


Moving to another example:

- RotationGate($\theta$, $\phi$, $\alpha$): a gate that rotates the Bloch Sphere by angle $\alpha$ along an axis with polar angle $\theta$ and azimuthal angle $\phi$.

Let us make a Hadamard using this class. This means that the axis is $\phi=0$ and $\theta=45^\circ$, and the angle of rotation is $\alpha=180^\circ$.

In [7]:
theta = np.pi/4
phi = 0
alpha = np.pi


another_hadamard = gates.RotationGate(theta, phi, alpha)

check_another_array = another_hadamard.get_array()
print('The gate takes the form: \n', check_another_array)

The gate takes the form: 
 [[6.123234e-17-0.70710678j 0.000000e+00-0.70710678j]
 [0.000000e+00-0.70710678j 6.123234e-17+0.70710678j]]


Enough Hadamards. Let us have a look at controlled gates.

- ControlledGate2($c$, gate): a 2-qubit controlled gate with the control qubit on position $c$ and a 1-qubit target gate. Note that this is a gate rather than an array.

Let us make a CNOT gate, where the control is $c=1$ (first qubit) and the target gate is
\begin{equation}
X =
\begin{pmatrix}
0 & 1 \\
1 & 0 \\
\end{pmatrix},
\end{equation}
which means that we want a gate of the form 
\begin{equation}
\text{CNOT} =
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
\end{pmatrix}.
\end{equation}

This goes as follows:

In [8]:
control = 1
x_gate = gates.XGate()

cnot_gate = gates.ControlledGate2(control, x_gate)

# The gate returns the desired matrix:
check_cnot_array = another_hadamard.get_array()
print('The CNOT gate takes the form: \n', check_cnot_array)

The CNOT gate takes the form: 
 [[6.123234e-17-0.70710678j 0.000000e+00-0.70710678j]
 [0.000000e+00-0.70710678j 6.123234e-17+0.70710678j]]


And naturally, there is an in-built gate for the CNOT as well: the CNOTGate2($c$).

In [9]:
builtin_cnot_gate = gates.CNOTGate2(control)
print('The builtin CNOT gate takes the form: \n', builtin_cnot_gate.get_array())

The builtin CNOT gate takes the form: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


Let us prove the following equivalence using code: $HZH = X$.

First, create instances of the gates:

In [10]:
x_gate = gates.XGate()
z_gate = gates.ZGate()
h_gate = gates.HGate()

Now, we extract the matrix forms by applying the method get_array().

In [11]:
x_array = x_gate.get_array()
z_array = z_gate.get_array()
h_array = h_gate.get_array()

Finally, we check that the equivalence is correct by using the numpy function `np.isclose()`. We use `np.isclose()` rather than np.array_equal() because there are small errors that add up from calculation with irrational numbers such as $\sqrt{2}$.

In [12]:
# HZH product.
hzh_prod = h_array @ z_array @ h_array
print('HZH product is approximately: ', hzh_prod)

print('This should be almost equal to Z, which is: ', z_array)

print('Checking directly with code: ', np.all(np.isclose(hzh_prod, z_array)))

HZH product is approximately:  [[-2.23711432e-17  1.00000000e+00]
 [ 1.00000000e+00 -2.23711432e-17]]
This should be almost equal to Z, which is:  [[ 1  0]
 [ 0 -1]]
Checking directly with code:  False


This completes the crash-course in the gates module.